#!/usr/bin/env python310
#coding:utf-8


from IPython.core.display import display
from datetime import datetime
import pandas as pd
import pygsheets

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import warnings
warnings.filterwarnings('ignore')

import fgc_uk
import fgc_ie
import fgc_fr

def read_from_google_sheet(): #define Python function

    client = pygsheets.authorize(service_file= 'D:/Python_Deployments/FGC_Automate_Email/Universal_Client_Secret.json')

    sh = client.open('FGC_FGCL_REPORT_2021_22')
    
    wks0 = sh.worksheet('title', 'Summary')

    wks1 = sh.worksheet('title', 'All_Geo')

    wks2 = sh.worksheet('title', 'UK_Topline')

    wks3 = sh.worksheet('title', 'IE_Topline')

    wks4 = sh.worksheet('title', 'FR_Topline')

    dfr1 = wks0.get_as_df(start = "B4", has_header = True, end = "K8", numerize = True) #Summary READING FROM GOOGLE SHEET
    
    dfr2 = wks0.get_as_df(start = "M4", has_header = True, end = "s8", numerize = True) #Summary READING FROM GOOGLE SHEET

    dfr3 = wks0.get_as_df(start = "U4", has_header = True, end = "AA8", numerize = True) #SUMMARY READING FROM GOOGLE SHEET

    dfr4 = wks1.get_as_df(start = "B4", has_header = True, end = None, numerize = True) #All Geo READING FROM GOOGLE SHEET

    dfr4 = dfr4.tail(n=3)

    dfr5 = wks2.get_as_df(start = "B4", has_header = True, end = None, numerize = True) #UK Topline READING FROM GOOGLE SHEET

    dfr5 = dfr5.tail(n=3)

    dfr6 = wks3.get_as_df(start = "B4", has_header = True, end = None, numerize = True) #IE Topline READING FROM GOOGLE SHEET

    dfr6 = dfr6.tail(n=3)

    dfr7 = wks4.get_as_df(start = "B4", has_header = True, end = None, numerize = True) #FR Topline READING FROM GOOGLE SHEET

    dfr7 = dfr7.tail(n=3)

    dfr8 = fgc_uk.read_query()

    dfr9 = fgc_ie.read_query()

    dfr10 = fgc_fr.read_query()

    dfrhtml1 = dfr1.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    dfrhtml2 = dfr2.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    dfrhtml3 = dfr3.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    dfrhtml4 = dfr4.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    dfrhtml5 = dfr5.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    dfrhtml6 = dfr6.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    dfrhtml7 = dfr7.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    dfrhtml8 = dfr8.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    dfrhtml9 = dfr9.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')
    
    dfrhtml10 = dfr10.to_html(justify = 'center', index = False).replace('<th>','<th style = "background-color: black; color:white; weight:bold">')

    now = datetime.now()

    dt_string = now.strftime("%d %B, %Y")
       
    '''
        Sending Email uisng SMTP outlook

    '''

    sender = "reports@feelgoodcontacts.com "

    recievers = ["nimit@fabelservices.net","dip@fabelservices.net","sp@fabelservices.net","vignesh@feelgoodcontacts.com","jay@fabelservices.net"]

    #recievers = ["nimit@fabelservices.net", "dip@fabelservices.net"]

    msg = MIMEMultipart('multipart')

    msg['Subject'] = "FGC FGCL REPORT 2021-22" + "-" + "  " + dt_string

    msg['From'] = sender

    msg['To'] = ",".join(recievers)
   
    msg.attach(MIMEText("<br></br>" + "<h3 style = 'text-decoration: underline; text-align:center'><b>FGCL DAILY REPORT Summary</b></h3>" + "<br></br>" + "<p><b>Revenue & Orders</b></p>" + dfrhtml1 + "<br></br>" + "<p><b>Registration</b></p>" + dfrhtml2 + "<br></br>" + "<p><b>Predictions</b></p>" + dfrhtml3 + "<br></br>" + "<p><b>All Geo</b></p>" + dfrhtml4 + "<br></br>" + "<p><b>UK Topline</b></p>" + dfrhtml5  + "<br></br>" + "<p><b>IE Topline</b></p>" + dfrhtml6 + "<br></br>" + "<p><b>FR Topline</b></p>" + dfrhtml7  + "<br></br>" + "<p><b>Daily UK</b></p>" + dfrhtml8 + "<br></br>" + "<p><b>Daily IE</b></p>" + dfrhtml9 + "<br></br>" + "<p><b>Daily FR</b></p>" + dfrhtml10 + "<br></br>" + "<b>Generated by - FGC Automate Email Bot</b>" + " ",  'html'))

    mail = smtplib.SMTP('smtp.office365.com', 587)

    mail.ehlo()

    mail.starttls()

    mail.login('reports@feelgoodcontacts.com', 'Juza3181')

    mail.sendmail(sender, recievers, msg.as_string())

    mail.quit()

if __name__ == '__main__':
    read_from_google_sheet()